from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1392, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_video = QtWidgets.QFrame(self.centralwidget)
        self.frame_video.setGeometry(QtCore.QRect(10, 10, 1371, 541))
        self.frame_video.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_video.setLineWidth(2)
        self.frame_video.setMidLineWidth(0)
        self.frame_video.setObjectName("frame_video")
        self.label_distance = QtWidgets.QLabel(self.centralwidget)
        self.label_distance.setGeometry(QtCore.QRect(510, 570, 101, 31))
        self.label_distance.setFrameShape(QtWidgets.QFrame.Box)
        self.label_distance.setLineWidth(2)
        self.label_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_distance.setObjectName("label_distance")
        self.label_EA = QtWidgets.QLabel(self.centralwidget)
        self.label_EA.setGeometry(QtCore.QRect(510, 610, 101, 31))
        self.label_EA.setFrameShape(QtWidgets.QFrame.Box)
        self.label_EA.setLineWidth(2)
        self.label_EA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EA.setObjectName("label_EA")
        self.label_AA = QtWidgets.QLabel(self.centralwidget)
        self.label_AA.setGeometry(QtCore.QRect(510, 650, 101, 31))
        self.label_AA.setFrameShape(QtWidgets.QFrame.Box)
        self.label_AA.setLineWidth(2)
        self.label_AA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AA.setObjectName("label_AA")
        self.textEditDis = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditDis.setGeometry(QtCore.QRect(710, 570, 91, 31))
        self.textEditDis.setFrameShape(QtWidgets.QFrame.Box)
        self.textEditDis.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEditDis.setObjectName("textEditDis")
        self.textEditEA = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEA.setGeometry(QtCore.QRect(710, 610, 91, 31))
        self.textEditEA.setFrameShape(QtWidgets.QFrame.Box)
        self.textEditEA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEditEA.setObjectName("textEditEA")
        self.textEditAA = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditAA.setGeometry(QtCore.QRect(710, 650, 91, 31))
        self.textEditAA.setFrameShape(QtWidgets.QFrame.Box)
        self.textEditAA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEditAA.setObjectName("textEditAA")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1392, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_distance.setText(_translate("MainWindow", "Distance"))
        self.label_EA.setText(_translate("MainWindow", "EA"))
        self.label_AA.setText(_translate("MainWindow", "AA"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())